name: "Bug Report"
description: "File a bug report"
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: environment
    attributes:
      label: Environment Name
      description: Is the bug occuring in a specific in environment or all environments?
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: URL
      description: URLs where this bug is occuring
    validations:
      required: false
  - type: textarea
    id: current-behavoir
    attributes:
      label: Current Behavoir
      description: What happens when this bug occurs?
    validations:
      required: true
  - type: textarea
    id: expected-behavoir
    attributes:
      label: Expected Behavour
      description: What is supposed to be happening? 
    validations:
      required: true
  - type: textarea
    id: error-message
    attributes:
      label: Error Message(s)
      description: Are there any error messages that you can see? Pls. copy/paste
    validations:
      required: true
 -  type: textarea
  attributes:
    label: Screenshots or videos
    description:
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

